name: Build
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: pnpm

    - name: Build
      run: |
        pnpm run build
        pnpm run docs

    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        publish_branch: gh-pages
        user_name: GitHub Action
        user_email: action@github.com
