name: Update
on:
  schedule:
  - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: yarn

    - name: Build
      run: |
        yarn install
        yarn run build

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com" && git config --global user.name "Github Action"
        git commit -am "Updated @tabler/icons" || (echo "No updates found" && exit 0)

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
